library(dplyr)
library(lubridate)
library(chron)
mydf <- read.table("household_power_consumption.txt", sep=";", stringsAsFactors = FALSE, header=TRUE)
mydf <- tbl_df(mydf)
data <- mutate(mydf, Date = dmy(Date))
data$Time <- strptime(data$Time, "%T")
data$Time <- times(format(data$Time, "%H:%M:%S"))
dates <- filter(data, Date=="2007-02-01" | Date=="2007-02-02")

dates$Sub_metering_1 <- as.numeric(dates$Sub_metering_1)
dates$Sub_metering_2 <- as.numeric(dates$Sub_metering_2)
dates$Sub_metering_3 <- as.numeric(dates$Sub_metering_3)

dates$date_time <- strptime(paste(dates$Date, dates$Time), "%Y-%m-%d %H:%M:%S")
dates$date_time <- as.POSIXct(dates$date_time)

png("plot3.png", width = 480, height=480)
par(bg=NA)
plot(dates$date_time, dates$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(dates$date_time, dates$Sub_metering_2, col="red", type="l")
lines(dates$date_time, dates$Sub_metering_3, col="blue", type="l")
legend("topright", lty=1, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lwd=2.5)
dev.off()
